### PR TITLE
Fix tree status updates not reflecting in UI

### LINKED ISSUE #454: AppBar doesn't change color when TreeBuildStatus changes
#452 introduced this feature.

Since the AppBar isn't using a state variable, it doesn't update.

### PR DESCRIPTION
**Pull request by CaseyHillers**
Fixes #454 

Issue was there was no state for the AppBar. This creates a parent widget for the build dashboard that maintains the state, and wraps its children in a ChangeNotifierProvider.

# Tested
I updated the fake cocoon service to give a random value for the tree status, and verified that the AppBar switched colors randomly every 10 seconds.

I think a regression test for this bug would involve writing an integration test, and that is out of the scope of this project.

### CODE REVIEW

File: app_flutter/lib/service/fake_cocoon.dart [hunk 1]
```diff
@@ -20,7 +22,7 @@ class FakeCocoonService implements CocoonService {
 
   @override
   Future<bool> fetchTreeBuildStatus() async {
-    return true;
+    return Random().nextBool();
```
Comment (jonahwilliams) [inline app_flutter/lib/service/fake_cocoon.dart]: Instead  of making this random  -  and therefore untestable, maybe make the value configurable for the fake?

File: app_flutter/lib/build_dashboard.dart [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+/// The tree's current build status is reflected in the color of [AppBar].
+/// The results from tasks run on individual commits is shown in [StatusGrid].
+class BuildDashboard extends StatelessWidget {
+  @override
+  Widget build(BuildContext context) {
+    final ThemeData theme = Theme.of(context);
+    return Consumer<FlutterBuildState>(
+      builder: (_, buildState, child) => Scaffold(
+        appBar: AppBar(
+          title: Text('Flutter Build Dashboard v2'),
```
Comment (jonahwilliams) [inline app_flutter/lib/build_dashboard.dart]: Did you turn on any of the lints that catch these?

```suggestion
          title: const Text('Flutter Build Dashboard v2'),
```

Comment (CaseyHillers) [reply app_flutter/lib/build_dashboard.dart]: https://github.com/flutter/cocoon/issues/455

Not yet, but that can get added today. Do you think this project should just use the flutter/flutter analysis options?

Comment (jonahwilliams) [reply app_flutter/lib/build_dashboard.dart]: Yeah, since it is a flutter project that makes sense. no need to do it in this PR

File: app_flutter/lib/service/fake_cocoon.dart (hunk 1 above)
Comment (CaseyHillers) [reply app_flutter/lib/service/fake_cocoon.dart]: I added a way  to inject it, so tests can inject their own "random" generator.
