### PR TITLE
Made it so dismissed approvals don't block the autosubmit bot.

### LINKED ISSUE #185224: `autosubmit` blocks merging on stale "request changes" pr
## example

https://github.com/flutter/flutter/pull/184984

## reproduction steps

1) X authors PR
1) Y reviews PR with request changes
1) X makes changes
1) Y approves changes
1) X fixes merge conflicts (which invalidates all previous approvals)
1) Z approves changes

In this state the PR just has one review that is an approval, but it will fail to merge the PR with the following message:

```
autosubmit label was removed for flutter/flutter/184984, because This PR has not met approval requirements for merging. Changes were requested by {Y}, please make the needed changes and resubmit this PR.
The PR author is a member of flutter-hackers and needs 1 more review(s) in order to merge this PR.

- Merge guidelines: A PR needs at least one approved review if the author is already part of flutter-hackers or two member reviews if the author is not a member of flutter-hackers before re-applying the autosubmit label. Reviewers: If you left a comment approving, please use the "approve" review action instead.
```

## observed behavior

The PR is blocked from merging, despite the PR having only one active review which is approval.

## expected behavior

Since Y's last review was approval, and the PR has an active review from Z, it should be merged.

### PR DESCRIPTION
**Pull request by gaaclarke**
fixes https://github.com/flutter/flutter/issues/185224

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

File: auto_submit/lib/validations/approval.dart [hunk 1]
```diff
@@ -180,15 +180,17 @@ class Approver {
...
         _changeRequestAuthors.add(authorLogin);
         if (_remainingReviews < targetReviewCount) {
           _remainingReviews++;
         }
+        _reviewAuthors.add(authorLogin);
+      } else if (state == DISMISSED_STATE && !_reviewAuthors.contains(authorLogin)) {
+        _reviewAuthors.add(authorLogin);
       }
-
-      _reviewAuthors.add(authorLogin);
```
Comment (b-luk) [inline auto_submit/lib/validations/approval.dart:191]: With the existing code, `_reviewAuthors` is updated outside of the if/else for APPROVED or CHANGES_REQUESTED.

So for the DISMISSED case, `_reviewAuthors` is updated and would override a previous CHANGES_REQUESTED already, without your change. Right?

If so, I don't see how this would behave any differently for the case we see in https://github.com/flutter/flutter/pull/185226. It seems like the existing code already lets DISMISSED override a previous CHANGES_REQUESTED.

Does the new "DISMISSED review should override previous CHANGES_REQUESTED" test that you added pass even when running without the changes here?

Maybe the issue is something else, like DISMISSED reviews getting filtered out before getting to this code?

Comment (b-luk) [reply auto_submit/lib/validations/approval.dart:191]: This code
https://github.com/flutter/cocoon/blob/710bc917c7dc1c6af48a0954533fd88a2b825c44/auto_submit/lib/requests/graphql_queries.dart#L70
seems like something that is requesting only APPROVED and CHANGES_REQUESTED reviews, and wouldn't return DISMISSED ones. Maybe this is related.

Caveat: I have no context for any of this code, so it's possible this is something totally unrelated.

**Comment by b-luk** [comment]
Also, not directly related to this change, but I notice that the UI lets me dismiss a REQUESTED_CHANGES review:
image

Does this mean that a REQUESTED_CHANGES review doesn't actually block an author from submitting, because they can always just dismiss that review? So REQUESTED_CHANGES is more of a suggestion than something that is enforceed?

Or is this UI something most people don't have, and I just see it because I have elevated permissions?

**Comment by gaaclarke** [comment]
> Does this mean that a REQUESTED_CHANGES review doesn't actually block an author from submitting, because they can always just dismiss that review? So REQUESTED_CHANGES is more of a suggestion than something that is enforceed?

The requirement is that you have approval, not that there is no requests changes.  Dismissing requests changes should be used respectfully obviously.

File: auto_submit/lib/validations/approval.dart (hunk 1 above)
Comment (gaaclarke) [reply auto_submit/lib/validations/approval.dart:191]: Yea, after I put this into review too I thought it odd too.  I had convinced myself because the test looks exactly like our case.  I'm not sure it would fail without the change though.  I'll look through this again.

Comment (gaaclarke) [reply auto_submit/lib/validations/approval.dart:191]: Okay, looked at it.  I think you were right about graphql_queries.  Done.

Comment (b-luk) [reply auto_submit/lib/validations/approval.dart:191]: So we no longer even need the changes in this file, right? Because the graphql query ensures that the only review states we get here are APPROVED, REQUESTED_CHANGES, and DISMISSED. And with the original code, the behavior for all 3 of these cases is identical to the behavior when your changes are included.

Even if the changes in this file are optional, I think it's a little clearer to explicitly handle all 3 possible cases. So this seems fine to me.

File: auto_submit/test/validations/approval_test.dart [hunk 2]
```diff
@@ -389,6 +389,113 @@ void main() {
...
+        }
+      }
+      ''';
+
+      final result = await computeValidationResult(bugScenario);
+
+      expect(result.result, isTrue);
+    });
+
+    test('COMMENTED review should NOT clear previous CHANGES_REQUESTED', () async {
```
Comment (b-luk) [inline auto_submit/test/validations/approval_test.dart]: This is testing an impossible scenario, because our graphql query won't return a COMMENTED review. Maybe we can remove this test because it can be misleading.

**Review by b-luk — APPROVED** [review]
This looks good to me, but I have no experience with this code or with how it works. So please also get approval from someone else who is more familiar with this.

**Comment by gaaclarke** [comment]
friendly ping @jtmcdole

File: auto_submit/lib/validations/approval.dart [hunk 3]
```diff
@@ -180,15 +180,18 @@ class Approver {
         if (_remainingReviews > 0) {
           _remainingReviews--;
         }
+        _reviewAuthors.add(authorLogin);
       } else if (state == CHANGES_REQUESTED_STATE &&
           !_reviewAuthors.contains(authorLogin)) {
         _changeRequestAuthors.add(authorLogin);
         if (_remainingReviews < targetReviewCount) {
           _remainingReviews++;
         }
```
Comment (jtmcdole) [inline auto_submit/lib/validations/approval.dart:189]: Nit: Interesting: if you get 3 approvals, you can ignore the the changes requested status. I think that's fine, but it would be nice to have a strong DO NOT SUBMIT or weigh Owners vs random teammates trying to be helpful.

**Review by jtmcdole — APPROVED** [review]

**Comment by gaaclarke** [comment]
I tried merging main because `ci.yaml validation` was stuck.  Now things that were passing are failing.  I think cocoon ci is sick.

File: auto_submit/lib/validations/approval.dart (hunk 3 above)
Comment (b-luk) [reply auto_submit/lib/validations/approval.dart:189]: 3 approvals does not cause a changes requested status to be ignored.

The code still calls `_changeRequestAuthors.add(authorLogin)`, and the `_approved =` check at the end requires `_changeRequestAuthors` to be empty.

I do think this code is pretty confusing though.

**Comment by jtmcdole** [comment]
> I tried merging main because `ci.yaml validation` was stuck. Now things that were passing are failing. I think cocoon ci is sick.

I suspect GitHub was sick.
